### ISSUE TITLE
/bin/sh: 1: ouxml_units: not found

### ISSUE THREAD

**Issue by mkalz** [innovationOUtside/open-ouxml-tools#4]
I followed the instructions and try to run the cells in mybinder, but get an error message. Did I miss an interim step?

**Comment by psychemedia** [comment]
Ah...  the package wasn't being installed since I changed the Binder setup. Fixed by https://github.com/innovationOUtside/open-ouxml-tools/commit/c0913202e4e37d12a71489a82796d7611ed0ae3a.
